
USE myFictionalBusiness; 

GO
ALTER TABLE Inventory WITH CHECK
ADD CONSTRAINT fk_SupplierID FOREIGN KEY(SupplierID) REFERENCES Suppliers(SupplierID)
ON UPDATE CASCADE
GO
ALTER TABLE Customers WITH CHECK
ADD CONSTRAINT fk_ZipCode FOREIGN KEY (ZipCode) REFERENCES ZipCode(ZipCode)
ON UPDATE CASCADE
GO
ALTER TABLE Sales WITH CHECK
ADD CONSTRAINT fk_CustomerID FOREIGN KEY(CustomerID) REFERENCES Customers(CustomerID)
ON UPDATE CASCADE
GO
ALTER TABLE SaleDetail WITH CHECK
ADD CONSTRAINT fk_OrderID FOREIGN KEY (OrderID) REFERENCES Sales(OrderID)
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE SaleDetail WITH CHECK
ADD CONSTRAINT fk_ProductID FOREIGN KEY (ProductID) REFERENCES Inventory(ProductID)



